[registry]
  [registry."localhost:32000"]
    http = true
    insecure = true
  [registry."127.0.0.1:32000"]
    http = true
    insecure = true
  [registry."192.168.1.211:32000"]
    http = true
    insecure = true
