apiVersion: v1
kind: PersistentVolume
metadata:
  name: urbansound-pv
spec:
  capacity:
    storage: ${PVC_SIZE}
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: ${USB_PATH}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["${NODE_NAME}"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: urbansound-data
  namespace: urbansound
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: ""
  resources:
    requests:
      storage: ${PVC_SIZE}
  volumeName: urbansound-pv

